### ISSUE TITLE
Resource slug and fingerprint is now exposed in the backend

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold-docs#12]
See https://github.com/ManifoldScholar/manifold/pull/1022

Not sure if this affects docs or not; if we have a page that lists resource backend fields, it should probably be updated.

**Comment by tsmyre** [comment]
Closed with https://github.com/ManifoldScholar/manifold-docs-jekyll/commit/5e1cb5bfb617c161830ee79b0fe3153b27d823e1
