### ISSUE TITLE
Error installing Manfold tag 5.1.3 using Docker Engine

### ISSUE THREAD

**Issue by jimgroom** [ManifoldScholar/manifold-docs#133]
Hi good folks of Manifold, 

I tried installing Manifold using Docker via Docker Engine and ran into the following error when trying to compose the file:
ERROR: manifest for manifoldscholarship/manifold-api:v5.1.3 not found: manifest unknown: manifest unknown

Not sure if I am doing something wrong, or if I should post this elsewhere, but thanks for any guidance and big fan!

**Comment by zdavis** [comment]
Look who the cat dragged in.

**Comment by zdavis** [comment]
I think this is a dupe of #130. @jimgroom, try it with with the v5.1.4-beta.1 tag.

best,
Zach

**Comment by jimgroom** [comment]
damn you are good and fast! That worked, I love you!

**Comment by zdavis** [comment]
Happy to help!
