### ISSUE TITLE
Consider mentioning new audio player in documentation

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold-docs#14]
See https://github.com/ManifoldScholar/manifold/pull/1003

**Comment by tsmyre** [comment]
I updated the reading section with notes on how to engage with and place resources, with sections devoted to the various viewers and players native to the platform [here](https://github.com/ManifoldScholar/manifold-docs-jekyll/commit/578d08c3285bac93d08c8dd4c9801ba942789249).
