### ISSUE TITLE
Document project slug field

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold-docs#15]
We exposed the project slug here: https://github.com/ManifoldScholar/manifold/pull/993

**Comment by tsmyre** [comment]
Closed with https://github.com/ManifoldScholar/manifold-docs-jekyll/commit/5e1cb5bfb617c161830ee79b0fe3153b27d823e1

**Comment by tsmyre** [comment]
Closed with https://github.com/ManifoldScholar/manifold-docs-jekyll/commit/5e1cb5bfb617c161830ee79b0fe3153b27d823e1
