### ISSUE TITLE
Document new html/google doc ingestion options

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold-docs#19]
This will be merged in soon and contains a number of additions, which can be seen in more detail on https://github.com/ManifoldScholar/manifold/pull/1049.  

Contains:
https://github.com/ManifoldScholar/manifold/issues/1077
https://github.com/ManifoldScholar/manifold/issues/1070
https://github.com/ManifoldScholar/manifold/issues/1040

**Comment by tsmyre** [comment]
Closed with #27.
