### ISSUE TITLE
Add OS version to package download instructions for Installing Manifold>On Ubuntu>Upgrades page

### ISSUE THREAD

**Issue by rlzevallos** [ManifoldScholar/manifold-docs#46]
On the Upgrades page under Installing Manifold/Ubuntu there is only one instruction/link for downloading the package, which doesn't specify which version of Ubuntu it's for. It would be more clear if it had a title (and bonus if it had the Ubuntu 16 link as well) as it displays on the Installation page.

Ubuntu Upgrades page:
![image 8](https://user-images.githubusercontent.com/26172306/48871745-39349680-eda3-11e8-9898-8ccd4e2000e0.png)

Ubuntu Installation page:
![image 7](https://user-images.githubusercontent.com/26172306/48871759-494c7600-eda3-11e8-9f75-af32d06d68e6.png)

**Comment by tsmyre** [comment]
Closed with #59.
