### ISSUE TITLE
Document smart project collection caching in 3.1

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold-docs#71]
We'll want to document some new behavior for v3.1:

Starting in v3.1, manifold will update the list of projects in smart collections every 15 minutes. Prior to 3.1, Manifold attempts to update the projects in collections every time a project changes, but it's difficult to do this with consistency. Saving a smart project collection will also refresh the cache of projects in that collection.

**Comment by tsmyre** [comment]
Closed with #80.
