### ISSUE TITLE
Document standalone projects

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold-docs#78]
The Standalone Project branch (ManifoldScholar/manifold#2296) will introduce some changes that need to be documented. I will summarize them here.

## For Projects:
- Fields on the backend/project/general form are reorganized a bit. I've renamed the top field group to "general attributes" and moved publication date and the thumbnail picker to that group so they are more prominent.
- There is a new "standalone mode" field under the "visibility" field group. The three options for this are disabled (default), enabled, and enforced. If standalone mode is disabled, the project can never be viewed in standalone mode. If standalone mode is enabled, the user must come to that project with `?mode=standalone` appended to the URL. If standalone mode is enforced, that project can only be viewed in standalone mode.
- I've changed the field group on this from that was called "other" to "taxonomy", and it now contains the subjects and tags fields.
- I've added a new set of fields under "press header bar" on this form. These fields allow the user to set the "press header" text and url on a project-by-project basis.

![manifold lvh_backend_projects_fcc2bb4d-6a16-4fca-b6de-490dd4bd49da_general(capture-desktop)](https://user-images.githubusercontent.com/255909/62170325-e58a2d80-b2df-11e9-86cf-0b7af85378d0.png)

## For Settings:
- On settings/themes, there are four new fields grouped under "press header bar". These fields control the text, color, link URL and behavior of the new press bar in the header.
- The possible display modes are disabled, always visible, and only visible in standalone mode. If enabled, the press header will always display. Press headers must have text and URL provided to display.  

![image](https://user-images.githubusercontent.com/255909/62170455-474a9780-b2e0-11e9-87cd-99fae42989c4.png)

The press header appears above the header on the frontend:

![image](https://user-images.githubusercontent.com/255909/62170706-41a18180-b2e1-11e9-85d1-3e96932c2cde.png)

![image](https://user-images.githubusercontent.com/255909/62170817-9e9d3780-b2e1-11e9-8117-9784e0b323d0.png)

## Standalone mode, generally:

A few things to note about standalone mode:

- The library header goes away and is replaced with the standalone header
- On the project home page, the standalone header appears on scroll
- Search in the project is scoped to the project
- The reader menu only includes a link to the project
- Project subpages show the standalone header, and no breadcrumbs
- The standalone header will respect whether the project hero is set to light or dark mode.

I'll add more to this issue as needed. Hopefully this helps a bit with documentation.

**Comment by tsmyre** [comment]
Closed with #79.
